stages:
- template: ffi-builds-templates/ffi-stage-template.yml
  parameters:
    dependency: webrtc_win_x64
    stageName: Build_Windows_x64
    jobName: Windows_x64
    os: windows-latest
    target: x86_64-pc-windows-msvc
    platform: windows
    jar: ''
    dylib: livekit_ffi.dll
    name: ffi-windows-x86_64
    artifact: webrtc-win-x64-release
    pool_name: agent-pool-windows2019-vmss
    envVars: ${{ parameters.envVars }}
    arch: ''
    buildScript: |
      cd livekit-ffi
      cargo build --release --target x86_64-pc-windows-msvc

- template: ffi-builds-templates/ffi-stage-template.yml
  parameters:
    dependency: webrtc_android_arm
    stageName: Build_Android_ARMV7
    jobName: Android_ARMV7
    os: ubuntu-latest
    target: armv7-linux-androideabi
    platform: android
    jar: libwebrtc.jar
    dylib: liblivekit_ffi.so
    name: ffi-android-armv7
    artifact: webrtc-android-arm-release
    pool_name: agent-pool-ubuntu2204-vmss
    envVars: ${{ parameters.envVars }}
    arch: armeabi-v7a
    buildScript: |
      cd livekit-ffi/
      cargo install cargo-ndk
      cargo ndk --bindgen --target armv7-linux-androideabi build --release --no-default-features --features "rustls-tls-webpki-roots"

- template: ffi-builds-templates/ffi-stage-template.yml
  parameters:
    dependency: webrtc_android_arm64
    stageName: Build_Android_ARMV8
    jobName: Android_ARMV8
    os: ubuntu-latest
    target: aarch64-linux-android
    platform: android
    jar: libwebrtc.jar
    dylib: liblivekit_ffi.so
    name: ffi-android-arm64
    artifact: webrtc-android-arm64-release
    pool_name: agent-pool-ubuntu2204-vmss
    envVars: ${{ parameters.envVars }}
    arch: arm64-v8a
    buildScript: |
      cd livekit-ffi/
      cargo install cargo-ndk
      cargo ndk --bindgen --target aarch64-linux-android build --release --no-default-features --features "rustls-tls-webpki-roots"

