stages:
- template: ffi-builds-templates/ffi-stage-template.yml
  parameters:
    stageName: Build_Windows_x64
    jobName: Windows_x64
    os: windows-latest
    target: x86_64-pc-windows-msvc
    platform: windows
    jar: ''
    dylib: livekit_ffi.dll
    name: ffi-windows-x86_64
    pool_name: agent-pool-windows2019-vmss
    envVars: ${{ parameters.envVars }}
    buildScript: |
      cd livekit-ffi
      cargo build --release --target x86_64-pc-windows-msvc

- template: ffi-builds-templates/ffi-stage-template.yml
  parameters:
    stageName: Build_Windows_ARM64
    jobName: Windows_ARM64
    os: windows-latest
    platform: windows
    jar: ''
    target: aarch64-pc-windows-msvc
    dylib: livekit_ffi.dll
    name: ffi-windows-arm64
    pool_name: agent-pool-windows2019-vmss
    envVars: ${{ parameters.envVars }}
    buildScript: |
      cd livekit-ffi
      cargo build --release --target aarch64-pc-windows-msvc --no-default-features --features "native-tls"

- template: ffi-builds-templates/ffi-stage-template.yml
  parameters:
    stageName: Build_Android_ARMV7
    jobName: Android_ARMV7
    os: ubuntu-latest
    target: armv7-linux-androideabi
    platform: android
    jar: libwebrtc.jar
    dylib: liblivekit_ffi.so
    name: ffi-android-armv7
    pool_name: agent-pool-ubuntu2204-vmss
    envVars: ${{ parameters.envVars }}
    buildScript: |
      cd livekit-ffi/
      cargo install cargo-ndk
      cargo ndk --bindgen --target armv7-linux-androideabi build --release --no-default-features --features "rustls-tls-webpki-roots"

- template: ffi-builds-templates/ffi-stage-template.yml
  parameters:
    stageName: Build_Android_ARMV8
    jobName: Android_ARMV8
    os: ubuntu-latest
    target: x86_64-linux-android
    platform: android
    jar: libwebrtc.jar
    dylib: liblivekit_ffi.so
    name: ffi-android-arm64
    pool_name: agent-pool-ubuntu2204-vmss
    envVars: ${{ parameters.envVars }}
    buildScript: |
      cd livekit-ffi/
      cargo install cargo-ndk
      cargo ndk --bindgen --target x86_64-linux-android build --release --no-default-features --features "rustls-tls-webpki-roots"

