# Azure DevOps Pipeline

trigger:
  tags:
    include:
      - "v*"
  branches:
    exclude:
      - '*'

resources:
  repositories:
    - repository: ci
      type: github
      endpoint: "forayo | PAT repo, admin:repo_hook"
      name: DisplayNote/qt-conan-ci
      ref: refs/tags/2.0.0

variables:
  - name: python.version
    value: '3.9'

stages:
  #- template: webrtc-builds.yml

  - template: ffi-builds.yml

  - template: prepare-conan-profile.yml
    parameters:
      dependencies: ['Build_Windows_x64', 'Build_Android_ARMV7', 'Build_Android_ARMV8']
      artifacts: ['ffi-android-arm64'] # xxx ->,  'ffi-android-armv7', 'ffi-windows-x86_64']
      packageName: livekit-ffi
      conanProfiles: ['msvc19.x86_64'] # xxx ->, 'android.arm64-v8a', 'android.armeabi-v7a']
