# Azure DevOps Pipeline

trigger:
  tags:
    include:
      - "v*"
  branches:
    exclude:
      - '*'

resources:
  repositories:
    - repository: ci
      type: github
      endpoint: "DisplayNote through PAT."
      name: DisplayNote/qt-conan-ci
      ref: refs/tags/2.0.2

variables:
  - name: python.version
    value: '3.9'


stages:
  - template: webrtc-builds.yml

  - template: ffi-builds.yml
