# Azure DevOps Pipeline

trigger:
  tags:
    include:
      - "v*"
  branches:
    exclude:
      - '*'

variables:
  - name: python.version
    value: '3.9'

stages:
  - template: webrtc-builds.yml

  - template: ffi-builds.yml
