stages:
- template: webrtc-builds.yml
  parameters:
    target_name: win
    os: windows-latest
    pool_name: agent-pool-windows2022-vmss
    cmd: build_windows.cmd
    arch: x64

- template: webrtc-builds.yml
  parameters:
    target_name: win
    os: windows-latest
    pool_name: agent-pool-windows2022-vmss
    cmd: build_windows.cmd
    arch: arm64

- template: webrtc-builds.yml
  parameters:
    target_name: android
    os: ubuntu-latest
    pool_name: agent-pool-ubuntu2204-vmss
    cmd: ./build_android.sh
    arch: arm

- template: webrtc-builds.yml
  parameters:
    target_name: android
    os: ubuntu-latest
    cmd: ./build_android.sh
    pool_name: agent-pool-ubuntu2204-vmss
    arch: arm64
