# Azure DevOps Pipeline

trigger:
  tags:
    include:
      - "v*"
  branches:
    exclude:
      - '*'

variables:
  - name: python.version
    value: '3.9'

stages:
- stage: build-webrtc
  displayName: Build WebRTC
  jobs:
  - job: BuildJob
    displayName: Build WebRTC
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        win_x64:
          target_name: win
          os: windows-2019
          cmd: .\build_windows.cmd
          arch: x64
        win_arm64:
          target_name: win
          os: windows-2019
          cmd: .\build_windows.cmd
          arch: arm64
        mac_x64:
          target_name: mac
          os: macos-13
          cmd: ./build_macos.sh
          arch: x64
        mac_arm64:
          target_name: mac
          os: macos-13
          cmd: ./build_macos.sh
          arch: arm64
        linux_x64:
          target_name: linux
          os: ubuntu-20.04 # Using ubuntu directly instead of buildjet
          cmd: ./build_linux.sh
          arch: x64
        linux_arm64:
          target_name: linux
          os: ubuntu-20.04 # Using ubuntu directly instead of buildjet
          cmd: ./build_linux.sh
          arch: arm64
        android_arm64:
          target_name: android
          os: ubuntu-20.04 # Using ubuntu directly instead of buildjet
          cmd: ./build_android.sh
          arch: arm64
        android_arm:
          target_name: android
          os: ubuntu-20.04 # Using ubuntu directly instead of buildjet
          cmd: ./build_android.sh
          arch: arm
        android_x64:
          target_name: android
          os: ubuntu-20.04 # Using ubuntu directly instead of buildjet
          cmd: ./build_android.sh
          arch: x64
        ios_device_arm64:
          target_name: ios
          out: ios-device-arm64
          os: macos-13
          cmd: ./build_ios.sh
          arch: arm64
        ios_simulator_arm64:
          target_name: ios
          out: ios-simulator-arm64
          os: macos-13
          cmd: ./build_ios.sh
          arch: arm64
          buildargs: --environment simulator
        release:
          profile: release
        debug:
          profile: debug

    steps:
    - task: Bash@3
      displayName: Setup variables
      env:
        DEFAULT_OUT: ${{ matrix.target_name }}-${{ matrix.arch }}
      inputs:
        targetType: 'inline'
        script: |
          OUT=$([string]::IsNullOrEmpty('${{ matrix.out }}') -eq $true ? '${{ env.DEFAULT_OUT }}' : '${{ matrix.out }}')-${{ matrix.profile }}
          echo "##vso[task.setvariable variable=OUT]$OUT"
          echo "##vso[task.setvariable variable=ZIP]webrtc-$OUT.zip"

    - task: Bash@3
      displayName: Info
      inputs:
        targetType: 'inline'
        script: |
          echo "OutName: $(OUT)"
          echo "OutZip: $(ZIP)"

    - task: UsePythonVersion@0
      displayName: Use Python $(python.version)
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - task: Bash@3
      displayName: Install setuptools
      inputs:
        targetType: 'inline'
        script: pip3 install setuptools

    - task: Bash@3
      displayName: Install linux dependencies
      condition: eq('${{ matrix.os }}', 'ubuntu-20.04')
      inputs:
        targetType: 'inline'
        script: |
          sudo apt update -y
          sudo apt install -y ninja-build pkg-config openjdk-11-jdk

    - task: Bash@3
      displayName: Install macos dependencies
      condition: eq('${{ matrix.os }}', 'macos-13')
      inputs:
        targetType: 'inline'
        script: brew install ninja

    - task: PowerShell@2
      displayName: Install windows dependencies
      condition: eq('${{ matrix.os }}', 'windows-2019')
      inputs:
        targetType: 'inline'
        script: |
          Invoke-WebRequest -Uri "https://github.com/ninja-build/ninja/releases/latest/download/ninja-win.zip" -OutFile ninja.zip
          Expand-Archive -Path ninja.zip -DestinationPath $(System.DefaultWorkingDirectory)\ninja
          Write-Host "##vso[task.setvariable variable=PATH]$(System.DefaultWorkingDirectory)\ninja;%PATH%"

    - task: Bash@3
      displayName: Print ninja version
      inputs:
        targetType: 'inline'
        script: ninja --version

    - checkout: self
      submodules: true

    - task: Bash@3
      displayName: Target OS
      inputs:
        targetType: 'inline'
        script: echo -e "\ntarget_os = [\"${{ matrix.target_name }}\"]" >> .gclient
        workingDirectory: $(System.DefaultWorkingDirectory)/webrtc-sys/libwebrtc

    - task: Bash@3
      displayName: Build WebRTC
      inputs:
        targetType: 'inline'
        script: ${{ matrix.cmd }} --arch ${{ matrix.arch }} --profile ${{ matrix.profile }} ${{ matrix.buildargs }}
        workingDirectory: $(System.DefaultWorkingDirectory)/webrtc-sys/libwebrtc

    - task: Bash@3
      displayName: Zip artifact (Unix)
      condition: ne('${{ matrix.os }}', 'windows-2019')
      inputs:
        targetType: 'inline'
        script: |
          cd $(System.DefaultWorkingDirectory)/webrtc-sys/libwebrtc
          zip $(System.DefaultWorkingDirectory)/$(ZIP) $(OUT) -r

    - task: PowerShell@2
      displayName: Zip artifact (Windows)
      condition: eq('${{ matrix.os }}', 'windows-2019')
      inputs:
        targetType: 'inline'
        script: Compress-Archive -Path $(System.DefaultWorkingDirectory)\webrtc-sys\libwebrtc\$(OUT) -DestinationPath $(System.DefaultWorkingDirectory)\$(ZIP)


    - task: PublishPipelineArtifact@1
      displayName: Publish Artifact
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/$(ZIP)'
        artifact: webrtc-builds
        publishLocation: 'pipeline'

- template: ffi-builds.yml
  dependsOn:
  parameters:
    envVars:
      LK_ARTIFACT_WEBRTC: '$(System.Artifac)'
