#ifndef livekit_ffi
#define livekit_ffi

/* Warning, this file is autogenerated. Don't modify this manually. */

#include <cstdarg>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

constexpr static const size_t BATCH_SIZE = 32;

/// # SAFTEY: The "C" callback must be threadsafe and not block
using FfiCallbackFn = void(*)(const uint8_t*, size_t);

using FfiHandleId = uint64_t;

constexpr static const FfiHandleId INVALID_HANDLE = 0;

extern "C" {

/// # Safety
///
/// The foreign language must only provide valid pointers
void livekit_ffi_initialize(FfiCallbackFn cb,
                            bool capture_logs,
                            const char *sdk,
                            const char *sdk_version);

/// # Safety
///
/// The foreign language must only provide valid pointers
FfiHandleId livekit_ffi_request(const uint8_t *data,
                                size_t len,
                                const uint8_t **res_ptr,
                                size_t *res_len);

bool livekit_ffi_drop_handle(FfiHandleId handle_id);

void livekit_ffi_dispose();

/// Probes whether the Android HW H264 encoder is on the SW-fallback blocklist,
/// stores the result, and returns it.  Must be called after WebRTC JNI
/// initialization and before the first room connection.
/// Always returns false on non-Android platforms.
bool livekit_ffi_probe_android_h264();

/// Explicitly sets whether the SW H264 encoder should be used instead of HW.
/// Call before the first room connection.  Always a no-op on non-Android
/// platforms.
void livekit_ffi_set_force_sw_h264(bool force);

}  // extern "C"

#endif  // livekit_ffi
